coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      default:
        target: 80%

  ignore:
    - "tests/*"
    - "**/__init__.py"
    - "**/*test*.py"
    - "**/test_*.py"
    - "setup.py"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: False
  require_head: True

flags:
  unittests:
    paths:
      - "backend/"
    carryforward: true